### ISSUE TITLE
USSD codes description in the history

### ISSUE THREAD

**Issue by morfikov** [mhogomchungu/ussd-gui#2]
ussd-gui has some history of entered USSD codes. Unfortunately, the codes sometimes are complicated and hard to memorize. In `modem-manager-gui` there was an option to specify a description for each USSD code. Actually, there was an option which allowed to add codes and set their description. Would you add this kind of feature to ussd-gui?

**Comment by mhogomchungu** [comment]
That sounds like a good idea,will implement it at some point in the new future.

**Comment by mhogomchungu** [comment]
git version now offers the functionality you requested so i am closing this bug report.

Will appreciate if you could test and report that the feature works.

To activate it,click the history button and then select "USSD Code Description" and i what will follow will be self explanatory.

**Comment by morfikov** [comment]
I just tested, two things:

1 Is there a way to merge `history` with `description`? Now you have two separate options, but we need just one. For now there's no way to select a USSD code from `description`. The code with the description is there but grayed out. So it would be nice just to activate the code through `description` and remove `history` altogether.

2 My language uses some non ASCII characters. They look good in `ussd-gui` window, but in the config file I have something like this:

`ussdInfo=*111* - RBM - zarz\x105\x64zanie kontem\n`

In this case `zarządzanie` was rewritten to `zarz\x105\x64zanie`. Could that be fixed?

**Comment by mhogomchungu** [comment]
1. Combining them will be a problem because "history" keeps the last ten commands entered and hence it keeps changing every time a command is sent. I think i should do away with history and only show entries in the favorites.Somehow,i didnt think this way. Will get back to you on this one.
2. It seems like QSettings class somehow translates those texts behind the scenes. Does the GUI read and display them properly?

**Comment by morfikov** [comment]
Yes, in GUI everything looks just fine. The problem is only in the config file.

**Comment by mhogomchungu** [comment]
The git version now only show one list

**Comment by morfikov** [comment]
Now it looks a way better.

1 Could you add sorting by description?
2 You could also add columns so the output would be aligned and easier to read.

**Comment by mhogomchungu** [comment]
1. Latest git version now has an option to move individual entry up or down the list. I think this way is better than auto sorting.
2. I do not think the second one is possible

**Comment by morfikov** [comment]
1 When I click the left mouse button on some entry in favorites, should the menu appear? I just got used to this action on the right mouse button, and it's kind of weird.
2. Would you add buttons instead of the menu? So, for instance, there's `add` button, I would add also `remove`, `edit`, `up` and `down`. In this case, you would just select an entry with a mouse, and then click the appropriate button.
3. I think there's no need for auto sorting now.

**Comment by mhogomchungu** [comment]
1. The menu appear on both left and right click in Qt4 but appears on left click only in Qt5.This is a change in Qt5. The menu should appear every time you left click a entry on the list.

**Comment by morfikov** [comment]
What about the buttons in favorites?

**Comment by mhogomchungu** [comment]
The bug report is still active so the request is being being worked on.

**Comment by mhogomchungu** [comment]
Just pushed a commit that added the buttons you requested.

To edit an entry,select the entry and then click the "edit" button and then make your edit on the entry fields and then click "add" button to commit your changes.

**Comment by morfikov** [comment]
Is there a way that the edited code would stay in the same position after editing?

**Comment by mhogomchungu** [comment]
done with the latest commit
