### ISSUE TITLE
Sending USSD codes by pressing enter key

### ISSUE THREAD

**Issue by morfikov** [mhogomchungu/ussd-gui#3]
There's a problem with sending USSD codes by pressing enter key on the keyboard. I have to use my mouse instead. Is there a way to fix that issue or am I forced to use the mouse?

**Comment by mhogomchungu** [comment]
The "S" at the "Send" button is underlined and this means you can press this button with "alt+s" key combo. I do not think clicking the "enter" button will work because you will probably be hitting the "enter" button when the "input" field has focus.

**Comment by morfikov** [comment]
Hmm, Alt+S is fine too. I thought it was just an "S" key, but it didn't work. I just didn't want to use my mouse.
