### ISSUE TITLE
Status: ERROR 5: Unknown Error Has Occured.

### ISSUE THREAD

**Issue by morfikov** [mhogomchungu/ussd-gui#6]
It looks like something is wrong when you open `ussd-gui` and press the `connect` button when some app is utilizing one of the interface of the modem. For instance, I started `gammu-smsd` daemon on one interface, and tried to start `ussd-gui` on the same interface. This always causes an error, because the interface is in use by the first app. So I killed the `gammu-smsd` daemon and tried to attach `ussd-gui` to that interface again. Now I got `Status: ERROR 5: Unknown Error Has Occured`.

There's no way to make it work again. It just gives the error above all the time, even when I reconnect the modem to the USB port. When I `cat` the device and connect via `ussd-gui`, I get the following:

```
ATZ
OK
AT+CUSD=1,"*111*480*3#",15
+CME ERROR: 304
AT+CUSD=2,,15
OK
TZ
OK
```

So there's `ATZ` command, the next is the code, but it results with an error.

The only way to fix the modem is by using the following command:

`$ echo -e "AT+CMGF=1;^CURC=0;^USSDMODE=0\r" > /dev/huawei-E3372-1`

Then `ussd-gui` works just fine.

**Comment by mhogomchungu** [comment]
Connecting to the internet using the modem while another tool is listening on the modem always breaks here so the problem is not only with ussd-gui.

I noticed the reason for this is because the modem removes each character that is read from it and hence only the first tool that will always get the character first will work and the rest will not because they will be expecting data that will never come because it was already taken by another tool.

Best advice i can give is to make sure only one tool is listening on the modem for things to work correctly.

Will add a config option to run a command after connecting so that you can reset your modem to your preferred state just after connecting.

**Comment by mhogomchungu** [comment]
Latest commit now supports sending a custom command after connecting when using the internal backend.

In your case,add the following line in the config file.

```
initCommand=AT+CMGF=1;^CURC=0;^USSDMODE=0
```

**Comment by morfikov** [comment]
Actually, I use NDIS (NCM) mode of my modem in order to connect to the internet. Also I have the`gammu-smsd` daemon active on `1`'st interface. And these two things work just fine. I can even add a third one, which is wammu. But here I have to watch out because my modem has only two interfaces and when I connect to `0`'th from wammu, then I won't be able to use NDIS(NCM) mode. But I can start the network connection in this mode first, and then it leaves the `0`'th interface alone and I can use it with `wammu`. So even though I have 2 interfaces, I'm able to use three things at the same time. It works pretty nice, but only `ussd-gui`has some issues with connecting and even when it has the whole device for itself.

I will test the new commit in a minute.

**Comment by morfikov** [comment]
It looks like that only part of the command was taken:

```
$ cat /dev/huawei-E3372-1
ATZ
OK
AT+CMGF=1
OK
```

Here actually you have 3 commands "AT+CMGF=1;^CURC=0;^USSDMODE=0"

```
AT+CMGF=1
AT^CURC=0
AT^USSDMODE=0

```

But you can pass them to the modem in the form which I do.

**Comment by morfikov** [comment]
You could also implement more than one init command. For instance, wvdial has 0-9.

**Comment by mhogomchungu** [comment]
change the line to this:

```
initCommand="AT+CMGF=1;^CURC=0;^USSDMODE=0"
```

It looks like Qt trancates the line after the first ";"

I think one line should be enough.

The application now also disables the "disconnect" button for two seconds when the button is clicked to disconnect.This should solve your problem of auto reconnecting.

**Comment by morfikov** [comment]
Ok, now the whole command is used, and `ussd-gui` works fine again. So I think, we can close this bug.
