### ISSUE TITLE
Prevent from adding the same entry in favorites

### ISSUE THREAD

**Issue by morfikov** [mhogomchungu/ussd-gui#7]
You can add two or more entries which are the same. I don't think this should happen. Instead, there should be some notification that would tell you there's a code on the list that you want to add.

**Comment by mhogomchungu** [comment]
git version now refuses to add a USSD code to the list if the code is found to already be present.

**Comment by morfikov** [comment]
Yes, that works nice too.

**Comment by morfikov** [comment]
1. I just realized that two different GSM operators can use the same USSD codes. Moreover, the same code can do different things depending on the GSM operator. So when you want to have the same codes for different GSM operators, there's no way to add them now. Still I think there should be some mechanism to prevent from adding the same code, but also `ussd-gui` should be able to distinguish different GSM operators. So how to handle this? I personally would add a third column that would allow to specify the name of the GSM operator. I just use the name in the code description now.
2. When you edit a code, you can specify the same code that is already on the list. I think this should also be fixed.

**Comment by mhogomchungu** [comment]
I have just found a work around for having the same USSD appearing more than once.

Add a space character at the end of the USSD code and the favorites feature will see this entry as a completely new USSD and will accept it but the functionality that sends USSDs will ignore the space character and will send the USSD code normally.

By adding space characters,you can have the same USSD appear in the favorites list as often as you want.

Your second point seems to also be a work around to having the same USSD appear twice.Just add a bogus entry the first time around and then edit it and add a USSD code that already exists.

**Comment by morfikov** [comment]
I think it would be better to just allow adding multiple instances of the same USSD code. You can type them anyway.
