### ISSUE TITLE
Support for the "delete" key in favorites

### ISSUE THREAD

**Issue by morfikov** [mhogomchungu/ussd-gui#9]
When you have many USSD codes in favorites, clicking on each and removing them individually is a little bit tiring. Wouldn't be easier to just press the `delete` key on the keyboard?

**Comment by mhogomchungu** [comment]
When the key is pressed,should a confirmation dialog pop up asking for confirmation or should the entry just be deleted?

**Comment by morfikov** [comment]
I think the confirmation is not necessary.

**Comment by mhogomchungu** [comment]
closing the bug report as "fixed",the delete button now deletes an entry in the favorite field without asking for a confirmation.

**Comment by morfikov** [comment]
There's just one issue with deleting an entry. When you select for instance an entry number 50 and press the `delete` key, the next entry to be deleted is the last one on the list. I think the selection should stay at the same position. The same issue is with the `delete` button.

**Comment by mhogomchungu** [comment]
done with the latest commit
